# Лабораторная работа 5. Структурированные типы данных

# Строки

Строки представляют собой последовательности символов. Длина строки ограничена лишь объемом оперативной памяти компьютера. 

Поддерживают обращение к элементу по индексу, получение среза, конкатенацию (оператор +), повторение (оператор *), а также проверку на вхождение (операторы in и not in).

Относятся к неизменяемым типам данных. Практически все операция в качестве значения возвращают новую строку. Поэтому для рациональной работы со строками желательно использовать специальные строковые методы.

Например, доступны следующие манипуляции:

In [1]:
s = "Hello, World!"
print(s, type(s), id(s))

Hello, World! <class 'str'> 1745890429808


In [2]:
s[-1] = "?"
print(s, type(s), id(s))

TypeError: 'str' object does not support item assignment

Для обозначения однострочечных символов (строк) можно использовать " " или ' ':

In [9]:
s = s[:-1] + "?" + '...'
print(s, type(s), id(s))

Hello, World?... <class 'str'> 1745891521840


Их комбинация задаёт ковычки в строке:

In [5]:
s = "Кто сказал " + '"Hello, World!"' + '?'
print(s, type(s), id(s))

Кто сказал "Hello, World!"? <class 'str'> 1741086040112


Для создания многострочечных строк используйте тройные ковычки:

In [12]:
s = """Строка 1
Строка 2
Строка 3
"""
print(s, type(s), id(s))

Строка 1
Строка 2
Строка 3
 <class 'str'> 2425413148208


Если строка не присваивается переменной, то она считается строкой документирования. Такая строка сохраняется в атрибуте_doc_того объекта, в котором расположена. 

Например:

In [34]:
def test():
    """Это описание функции"""
    pass

In [35]:
print (test.__doc__)

Это описание функции


Строковые методы.

Для строк есть множество методов. Посмотреть их можно по команде

In [13]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


Получить информацию по каждому можно следующим образом

In [14]:
help(str.split)

Help on method_descriptor:

split(self, /, sep=None, maxsplit=-1)
    Return a list of the words in the string, using sep as the delimiter string.
    
    sep
      The delimiter according which to split the string.
      None (the default value) means split according to any whitespace,
      and discard empty strings from the result.
    maxsplit
      Maximum number of splits to do.
      -1 (the default value) means no limit.



In [15]:
help(str.join)

Help on method_descriptor:

join(self, iterable, /)
    Concatenate any number of strings.
    
    The string whose method is called is inserted in between each given string.
    The result is returned as a new string.
    
    Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'



Рассмотрим наиболее интересные из них:
    
- метод split() позволяет разбить строку по указанному разделителю (по умолчанию - пробелам), в результате получается список слов;
- метод join() выполняет обратное действие, формирует из списка строку с определённым объединителем;
- метод format() выполняет запонение строки в зарезервированные {} места.

Например:

In [16]:
"Хорошо бы разделить эту строку на части".split()

['Хорошо', 'бы', 'разделить', 'эту', 'строку', 'на', 'части']

In [19]:
s = "Но не каждую строку, которую надо разделить, нужно делить по пробелам!!!"

In [20]:
s.split(', ')

['Но не каждую строку',
 'которую надо разделить',
 'нужно делить по пробелам!!!']

In [21]:
s.split('!')

['Но не каждую строку, которую надо разделить, нужно делить по пробелам',
 '',
 '',
 '']

In [25]:
s.split('!', 1)  #  ограничем максимальное чило делений

['Но не каждую строку, которую надо разделить, нужно делить по пробелам', '!!']

In [26]:
s2 = s.split(', ')
print(s2)

['Но не каждую строку', 'которую надо разделить', 'нужно делить по пробелам!!!']


In [31]:
s1 = ', '
print(s1, type(s1), id(s1))

,  <class 'str'> 2425412618352


In [33]:
s1 = s1.join(s2)
print(s1, type(s1), id(s1))

Но не каждую строку, которую надо разделить, нужно делить по пробелам!!! <class 'str'> 2425413268400


Строковый метод format() позволяет создать строку форматной вставкой в неё данных:

In [14]:
size = "length - {}, width - {}, height - {}"
size.format(3, 6, 2.3)

'length - 3, width - 6, height - 2.3'

In [11]:
size = "length - {2}, width - {0}, height - {1}"
size.format(3, 6, 2.3)

'length - 2.3, width - 3, height - 6'

In [41]:
size = "length - {length:5.3f}, width - {width:5.3f}, height - {height:5.3f}"
size.format(width=3.3333333, height=6.7896, length=2.3)

'length - 2.300, width - 3.333, height - 6.790'

# Списки

Список в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры). Эллементы списка доступны по индексу начинающегося с 0. Список является изменяемым типом данных - любой его эллемнт можно изменить.

Список задаётся перечислением его элементов в квадратных скобках через запятую или с помощью функции list(), например

In [17]:
List = [1, 2.0, '3', [4]]
List

[1, 2.0, '3', [4]]

In [18]:
List[2] = 'three'
List

[1, 2.0, 'three', [4]]

Списки поддерживают следующие базовые операции:

In [19]:
l=[0,1,2,3,4,5,6,7]
l

[0, 1, 2, 3, 4, 5, 6, 7]

- удаление эллемента

In [20]:
del l[3]
l

[0, 1, 2, 4, 5, 6, 7]

- добавить эллемента в заданную позицию

In [21]:
l.insert(3,0)
l

[0, 1, 2, 0, 4, 5, 6, 7]

- добавить эллемента в конец

In [22]:
l.append(8)
l

[0, 1, 2, 0, 4, 5, 6, 7, 8]

- добавить несколько эллементов в конец

In [23]:
print(l, type(l), id(l))
l.extend([9,10,11])
print(l, type(l), id(l))

[0, 1, 2, 0, 4, 5, 6, 7, 8] <class 'list'> 1745891244616
[0, 1, 2, 0, 4, 5, 6, 7, 8, 9, 10, 11] <class 'list'> 1745891244616


In [25]:
l = [6, 7]
print(l, type(l), id(l))
l = l + [4]
print(l, type(l), id(l))

[6, 7] <class 'list'> 1745890726536
[6, 7, 4] <class 'list'> 1745890726024


# Генераторы списков

Можно также воспользоваться генераторами списков:

In [11]:
x = [i for i in range(10)]
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Генераторы списков могут иметь сложную структуру — например, состоять из нескольких вложенных циклов for и (или) содержать оператор ветвления if после цикла. Для примера получим четные элементы списка и умножим их на 10:

In [12]:
x2 = [ i*10 for i in x if i%2 == 0 ]
print(x2)

[0, 20, 40, 60, 80]


Этот код эквивалентен коду:

In [59]:
x2 = []
for i in x:
    if i % 2 == 0: 
        x2.append(i*10) 
print(x2)

[0, 20, 40, 60, 80]


# Копирование списков

Операция копирования для листов, имеет особенности

In [50]:
y = x # это не копирование!!!
print(id(x), id(y))

2425413357064 2425413357064


Правильное копирование:

In [52]:
y1 = list(x)
y2 = x.copy()
y3 = x[:]

print(y1, id(y1))
print(y2, id(y2))
print(y3, id(y3))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413349128
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413247688
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 2425413354888


Объединение листов:

In [54]:
x = x[:2] + x[-2:]
print(x, type(x), id(x))

[0, 1, 8, 9] <class 'list'> 2425413318088


# Кортеж

Кортеж в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры).

Его эллементы доступны по индексу начинающегося с 0. Кортеж является не изменяемым типом данных - его эллемнты нельзя менять.

Кортеж задаётся перечислением его элементов в круглых скобках через запятую или с помощью функции tuple(), например

In [13]:
Tuple = (1, 2.0, '3', [4, 5])
print(Tuple[0],Tuple[1],Tuple[2],Tuple[3])

1 2.0 3 [4, 5]


In [14]:
Tuple[2] = 'three'
print(Tuple[0],Tuple[1],Tuple[2],Tuple[3])

TypeError: 'tuple' object does not support item assignment

In [16]:
Tuple[3]

[4, 5]

In [17]:
Tuple[3] = [1, 2]
Tuple[3]

TypeError: 'tuple' object does not support item assignment

In [18]:
Tuple[3][0]

4

In [19]:
Tuple[3][0]=-4
Tuple[3][0]

-4

# Множества

Множества в Python - это упорядоченный набор объектов, в который могут одновременно входить объекты разных типов (числа, строки и другие структуры). В отличии от списков и картежей, множество не итерируется по индуксу.

In [30]:
Set = set([2.0000000000000001, 1, 2, 1, '3', 4, 3])
Set

{1, 2.0, 3, '3', 4}

In [31]:
Set.add(-1)
Set

{-1, 1, 2.0, 3, '3', 4}

Почему пропала одна 1?

Вероятно, наиболее важной операцией с множеством является операция праверки принадлежности, и для неё нужно знать только уникальные эллементы множества. По этой же причине отсутствует возможность обращаться к эллементам по индексу.

In [11]:
x = 1

if x in Set:
    print('принадлежит множеству')
else:
    print('не принадлежит множеству')

принадлежит множеству


In [12]:
dir(set)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [13]:
help(set.add)

Help on method_descriptor:

add(...)
    Add an element to a set.
    
    This has no effect if the element is already present.



# Словари

Словарь в Python - структура содержит пары "ключ" - "значение" (их порядок несущественен). Это одина из наиболее полезных и гибких структур имеющихся в Python. Словари реализованы как хэш-таблицы, так что поиск даже в больших словарях очень эффективен.

Например, с помощью словоря можно эмулировать работу оператора множественного выбора аналогичного switch:

In [32]:
def switch_dict(x):
    return {
        "a": 1,
        "b": 2,
        "c": 3
    }.get(x, -1)

In [33]:
switch_dict('a')

1

In [34]:
switch_dict('6')

-1

In [35]:
ss = {1: "a","b": 2,"c": 3}

In [37]:
ss[1]

'a'

In [36]:
ss['b']

2

# Массивы (numpy)

Менее стандартной, но очень полезной является структура массив, объединяющая эллементы одинакового типа.

In [1]:
import numpy as np

In [39]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

Очень часто возникает задача создания массива определенного размера, причем чем заполнен массив абсолютно неважно. В этом случае можно воспользоваться циклами или генераторами списков (кортежей), но NumPy для таких случаев предлагает более быстрые и менее затратные функции-заполнители.

Полезными оказываются следующие функции (по умолчанию, тип создаваемого массива - float64.):

- zeros() - заполняет массив нулями, 

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros(3)

array([0., 0., 0.])

- eye() - создаёт единичную матрицу, 

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- empty - заполняет матрицу случайными числами, которые зависят от состояния памяти. 

In [43]:
np.empty([3, 3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Для создания последовательностей чисел NumPy предоставляет функции arange() и linspace(), которая возвращает одномерные массивы:

- np.arange(From, To, Step) - построить массив чисел от From (включая) до To (не включая) с шагом Step:

In [44]:
np.arange(10)   #  От 0 до указанного числа с шагом 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(10, 20)    #  От 10 до 20 с шагом 1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
np.arange(10, 100, 10)    #  Диапазон с заданным шагом

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
np.arange(0, 1, 0.1)    #  Аргументы могут иметь тип float

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

- np.linspace(From, To, Num) - построить массив чисел от From (включая) до To (включая) с колличеством эллементов Num:

In [123]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [2]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
A[0,0] = 5.1

In [5]:
A = A/2

In [6]:
A

array([[2.5, 1. ],
       [1.5, 2. ]])

# Упражнение 1.

С клавиатуры (неограниченное количество раз) вводится некоторая последовательность значений, необходимо сохранить только уникальные символы (цифры и буквы). И после окончания ввода вывести сохранённые символы.

In [1]:
k=[]
s=set(k)

while 1>0:
    x=input()
    if x=='Персик':
        print(s)
        break
    s.add(x)

3
4
6
8
9
2
5
3
5
67
8
Персик
{'6', '2', '8', '67', '5', '4', '3', '9'}


# Упражнение 2. Эффективный размер массива (стек).

Стек, дека, очередь. Массив с дополнительными параметрами (размер выделенной памяти и объём занятой памяти). Позволяют за константное время добавлять и убирать элементы в начало и конец эффективного размера массива.

Напишите функцию которая реализует работу стека: 
1. внутри определён массив numpy заданного размера и целочисленный параметр фиксирующий степень заполненности массива;
2. функция принимает значение x и индиксатор действия (0 - чтение из стека, 1 - запись в стек); в случае чтения возвращает значение из конца массива или False, если стек пуст; при записи возвращает логическую переменную индикатор успешности операции;
3. при операциях чтения и записи должна проверяться корректность этого действия связанная с размерами стека.

In [23]:
import numpy as np

def fstack(id, x = 0):
    global istack
    if id == True:
        if istack == 0:
            return False
        else:
            istack = istack - 1
            tmp=stack[istack]
            stack[istack]=0
            return tmp
     
    else:
        if istack == nstack:
            return False
        else:
            stack[istack] = x
            istack+=1
            return True
       

In [24]:
from random import randint

nstack = 5
stack = np.zeros(nstack)
istack = 0

for i in range(30):
    x = randint(1,30)
    idd = randint(0,1)
    print(idd, fstack(idd,x), stack)
    

0 False [0. 0. 0. 0. 0.]
0 False [0. 0. 0. 0. 0.]
1 True [1. 0. 0. 0. 0.]
1 True [1. 1. 0. 0. 0.]
1 True [1. 1. 1. 0. 0.]
0 1.0 [1. 1. 0. 0. 0.]
1 True [1. 1. 1. 0. 0.]
0 1.0 [1. 1. 0. 0. 0.]
1 True [1. 1. 1. 0. 0.]
0 1.0 [1. 1. 0. 0. 0.]
1 True [1. 1. 1. 0. 0.]
0 1.0 [1. 1. 0. 0. 0.]
0 1.0 [1. 0. 0. 0. 0.]
1 True [1. 1. 0. 0. 0.]
0 1.0 [1. 0. 0. 0. 0.]
0 1.0 [0. 0. 0. 0. 0.]
0 False [0. 0. 0. 0. 0.]
1 True [1. 0. 0. 0. 0.]
0 1.0 [0. 0. 0. 0. 0.]
0 False [0. 0. 0. 0. 0.]
0 False [0. 0. 0. 0. 0.]
0 False [0. 0. 0. 0. 0.]
1 True [1. 0. 0. 0. 0.]
1 True [1. 1. 0. 0. 0.]
1 True [1. 1. 1. 0. 0.]
1 True [1. 1. 1. 1. 0.]
1 True [1. 1. 1. 1. 1.]
1 False [1. 1. 1. 1. 1.]
0 1.0 [1. 1. 1. 1. 0.]
1 True [1. 1. 1. 1. 1.]


# Упражнение 3. Эффективный размер массива (множество).

Как мы уже поняли, множество в Python это совокупность уникальных объектов недоступных по индексу. Адаптируйте предыдущую программу к работе в таком режиме.

Т.е.: 
1. дописываться могут только значения не записанные ранее;
2. функция принимает одно значение x (True - вывод всего множества, числовое значение - запись в множество); в случае если множество пусто возвращается False; при записи возвращает логическую переменную индикатор успешности операции;
3. при операциях чтения и записи должна проверяться корректность этого действия связанная с размерами множества.

P.S. Попробуйте реализовать пункт с выводом значений по возрастанию через работу с дополнительным массивом индексов (перестановок). Или начиная запись в множество с середины массива...

In [4]:
import numpy as np
from random import randint


def fst(x):
    global istack
    global stack
    global nstack
    
    if x == True:
        if istack == 0:
            return False
        else:
            return stack
    elif type(x) == int:
        if x in stack:
            x = int(input('Введите число: '))
            return fst(x)
        else:
            if istack == nstack:
                return 'Переполнение массива'
            
            stack[istack] = x
            istack += 1
            return True
nstack = 10
stack = np.zeros(nstack)
istack = 0

for i in range(20):
    x = randint(1,5)
    if i%5==0:
        x = True
    res = fst(x)
    print(x, res)
    print(stack)
    if res == 'Переполнение массива':
        break
   
    
#без сет
#массив перестановок

True False
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 False
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 False
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5 True
[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Введите число: 7


C:\Users\aleks\AppData\Local\Temp\ipykernel_5292\90025554.py:37: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if res == 'Переполнение массива':


5 True
[5. 7. 0. 0. 0. 0. 0. 0. 0. 0.]
True [5. 7. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 7. 0. 0. 0. 0. 0. 0. 0. 0.]
2 True
[5. 7. 2. 0. 0. 0. 0. 0. 0. 0.]
4 True
[5. 7. 2. 4. 0. 0. 0. 0. 0. 0.]
Введите число: 6
2 True
[5. 7. 2. 4. 6. 0. 0. 0. 0. 0.]
1 [5. 7. 2. 4. 6. 0. 0. 0. 0. 0.]
[5. 7. 2. 4. 6. 0. 0. 0. 0. 0.]
True [5. 7. 2. 4. 6. 0. 0. 0. 0. 0.]
[5. 7. 2. 4. 6. 0. 0. 0. 0. 0.]
Введите число: 6
Введите число: 7
Введите число: 8
5 True
[5. 7. 2. 4. 6. 8. 0. 0. 0. 0.]
Введите число: 8
Введите число: 8
Введите число: 8
Введите число: 8
Введите число: 8
Введите число: 8
Введите число: 86
2 True
[ 5.  7.  2.  4.  6.  8. 86.  0.  0.  0.]
3 True
[ 5.  7.  2.  4.  6.  8. 86.  3.  0.  0.]
1 [ 5.  7.  2.  4.  6.  8. 86.  3.  0.  0.]
[ 5.  7.  2.  4.  6.  8. 86.  3.  0.  0.]
True [ 5.  7.  2.  4.  6.  8. 86.  3.  0.  0.]
[ 5.  7.  2.  4.  6.  8. 86.  3.  0.  0.]
Введите число: 98
2 True
[ 5.  7.  2.  4.  6.  8. 86.  3. 98.  0.]
Введите число: 56
3 True
[ 5.  7.  2.  4.  6.  8. 86.  3. 98. 56.]
Введит

###### Функции для итерируемых объектов.

Наиболее полезными для итерируем объектов являются функции:
- map() - позволяет применить заданную функцию к каждому элементу последовательности, возвращает объект, поддерживающий итерации,
- zip() - возвращает кортеж, содержащий элементы последовательностей расположенных на одинаковом смещении,
- filter() - позволяет выполнить проверку элементов последовательности.

In [62]:
def fun(elem):
    return elem + 10 

arr = [1, 2, 3, 4, 5]
print(list(map(fun, arr)))

[11, 12, 13, 14, 15]


In [63]:
list(zip([ 1, 2, 3], [4, 5, 6], [7, 8, 9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [67]:
arrl = [1, 2, 3, 4, 5]
arr2 = [10, 20, 30, 40, 50]
arrЗ = [100, 200, 300, 400, 500]

arr = [х + у + z for (х, у, z) in zip(arrl, arr2, arrЗ)]
print(arr)

[111, 222, 333, 444, 555]


или что тоже самое

In [68]:
def fun(a,b,c):
    return a+b+c 

print(list(map(fun, arrl, arr2, arrЗ)))

[111, 222, 333, 444, 555]


In [69]:
def fun(elem):
    return elem % 2 == 0

list(filter(fun, arr))

[222, 444]

# Генераторы словарей

In [72]:
keys = ["а", "Ь", "c"]
values = [1, 2, 3] 
dict_kv = {k: v for (k, v) in zip(keys, values)}
dict_kv

{'а': 1, 'Ь': 2, 'c': 3}

# Упражнение 4.

Создайте функцию принимающую двумерную таблицу, работающую со всеми возможными итерируемыми типами данных подходящими для её хранения (лист, словарь, картеж, массив и т.д.). Функция должна выполнять вывод строк этой таблици в случайном порядке. 

Насколько сложно было бы сделать аналогичный вывод для столбцов?

In [ ]:
import random 
import numpy as np 
 
def tb(table):
    res = [0, 0]
    if type(table) is dict:
    result[0] = [ x for x in table.keys()]
    result[1] = [ x for x in table.values()]
    else:
    result[0] = [ x for x in table[0]]
    result[1] = [ x for x in table[1]]
    starLine = random.randint(0, 1)
    return result[starLine], result[not(starLine)]
 
print(tb({1:4, 2:5, 3:6}))
print(tb([[1,2,3],[4,5,6]]))
print(tb(tuple([[1,2,3],[4,5,6]])))
print(tb(np.array([[1,2,3],[4,5,6]])))

# Домашнее задание (базовое):

# Задание 1.

С клавиатуры вводится строка, включающая строчные и прописные буквы. Требуется вывести ту же строку в изменённом регистре, тип регистра зависит от того, каких букв больше. При равном количестве букв в заглавном и проптсном регистре - выводится оригинальная строка. 

Например, вводится строка "HeLLo World", она должна быть преобразована в "hello world", потому что в исходной строке малых букв больше. 

В программе можно использовать строковые методы: upper() (преобразование к верхнему регистру) и lower() (преобразование к нижнему регистру), isupper() и islower() (проверяющие регистр строки или символа).

In [8]:
s = input()
big_sum = 0
small_sum = 0
big_list = [i for i in 'QWERTYUIOPASDFGHJKLZXCVBNMЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ']
small_list = [i for i in 'qwertyuiopasdfghjklzxcvbnmйцукенгшщзхъфывапролджэячсмитьбю']
for k in range(len(s)):
    if s[k] in big_list:
        big_sum += 1
    elif s[k] in small_list:
        small_sum += 1
if big_sum > small_sum:
    print(s.upper())
elif small_sum > big_sum:
    print(s.lower())
else: 
    print(s)

лвпспоНГПРлuihdfjGYUGJKH
лвпспонгпрлuihdfjgyugjkh


# Задание 2

Дано слово "объектно-ориентированный". Используя индексацию и срезы составьте из него как можно больше слов "объект", "ориентир", "тир", "кот", "рента" и тд. Выведите их на экран.

In [12]:
from urllib.request import urlopen
from urllib.parse   import quote

word = input('Введите слово: ')
url = ("https://makeword.ru/combo/" + quote(word))

page = urlopen(url)
html_bytes = page.read()
html = html_bytes.decode("utf-8")
contentStart = html.find('<div class="ad_1"')
contentEnd = html.find('<div class="addthis_sharing_toolbox"')
html = html[contentStart:contentEnd]

def find_all(a_str, sub):
    start = 0
    while True:
        start = a_str.find(sub, start)
        if start == -1: return
        yield start
        start += len(sub)

for i in find_all(html, '<a'):
    endOpenTag = html.find('>', i)
    endTag = html.find('<', endOpenTag)
    print(html[endOpenTag+1:endTag])

NameError: name 'объектно' is not defined

# Задание 3

Строковый метод isdigit() проверяет, состоит ли строка только из цифр. Напишите программу, которая запрашивает с ввода целые числа и выводит их сумму. В случае некорректного ввода программа не должна завершаться с ошибкой, а должна продолжать работу, удаляя из введённой строки все символы кроме цифр. При отсутствии цифр запрс пользователю повторяется.

Обработчик исключений try-except использовать нельзя.

In [14]:
def hasDigits(s):
    for i in s:
        if i.isdigit(): return True
    return False

line = input('Введите числа: ')
while hasDigits(line):
    summ = 0
    for s in line:
        if s.isdigit():
            summ += int(s)
    print(summ)
    line = input('Введите числа(Или другие символы): ')

Введите числа(Или другие символы): 56
11
Введите числа(Или другие символы): 56
11
Введите числа(Или другие символы): 56
11
Введите числа(Или другие символы): 56
11
Введите числа(Или другие символы): 4с53мй3
15


KeyboardInterrupt: Interrupted by user

# Задание 4

Создайте словарь, где ключами являются числа, а значениями – строки. Примените к нему метод items(), полученный объект dict_items передайте в написанную вами функцию, которая создает и возвращает новый словарь, "обратный" исходному, т. е. ключами являются строки, а значениями – числа. 

In [15]:
s = 'abcdefghij'
x = {}
for i in range(len('1234567890')):
    x[i] = s[i]
print('Было: ', x)
def f(x):
    s = {}
    for k,v in x.items():
        s[v] = k
    return s
print('Cтало: ',f(x))

Было:  {0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j'}
Cтало:  {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9}


# Задание 5. (Снова в школу...)

Опишите структуру данных (базу данных) на основе словаря и интерфейс работы с ней (функцию). 

Создайте словарь school, и наполните его данными, которые бы отражали количество учащихся в разных классах (1а, 1б, 2б, 6а, 7в и т.п.). И функцию для внесения изменений в словарь в рамках следующего функционала: 
а) в одном из классов изменилось количество учащихся; 
б) в школе появился новый класс; 
с) в школе был расформирован (удален) класс, в связи с чем ученики были равномерно распределены по другим; 
d) выгрузка данных: общее количество учащихся в школе, общее колличество классав, распределение учеников по классам.

P.S. Дополнительно.

Подумайте как лучше всего хранить такую базу данных в файле. Попробуйте реализовать свою идею.

# Домашнее задание (дополнительное):

# Задание. Реверс словаря.

Создайте словарь, где ключами являются цифры, а значениями – строки. Передайте словарь в функцию, которая создает и возвращает новый словарь, "обратный" исходному, при этом ключами являются буквы составляющие строки, а значениями – числа составленные из цифр в порядке соответствующем.

Например: 

Исходный словарь: {1: 'аcc', 2: 'сab', 3: 'ccb'}

Выходной словарь: {'а': 12, 'b': 23, 'c': 11233}

# Задание. Разрезание таблиц. 

Заполните квадратную таблицу порядка n по спирали по часовой стрелке начиная с левого верхнего угла. В напишите функцию принимающую данную таблицу в подходящем формате, найдите строку с наибольшим количеством нулей и столбец с максимальной суммой элементов. Разрежьте по этой строке и столбцу таблицу и верните из функции получившийся результат как отдельные таблицы, после чего выведете их на печать.

# Задание. Пары.

На вход программы поступает последовательность из N целых положительных чисел, все числа в последовательности различны. Рассматриваются все пары различных элементов последовательности (элементы пары не обязаны стоять в последовательности рядом, порядок элементов в паре не важен). Необходимо определить количество пар, для которых произведение элементов делится на 26.
Описание входных и выходных данных.

В первой строке входных данных задаётся количество чисел N (1 ≤ N ≤ 1000). В каждой из последующих N строк записано одно целое положительное число, не превышающее 10 000.

В качестве результата программа должна напечатать одно число: количество пар, в которых произведение элементов кратно 26.

Пример входных данных: 4 2 6 13 39

Пример выходных данных: 4

Из четырёх заданных чисел можно составить 6 попарных произведений:

2·6 = 12 

2·13 = 26 

2·39 = 78 

6·13 = 78

6·39 = 234 

13·39 = 507

Из них на 26 делятся 4 произведения:

2·13=26

2·39=78

6·13=78

6·39=234

Требуется написать эффективную по времени и по памяти программу для решения описанной задачи.

(Программа считается эффективной по времени, если при увеличении количества исходных чисел N в k раз время работы программы увеличивается не более чем в k раз. Программа считается эффективной по памяти, если память, необходимая для хранения всех переменных программы, не превышает 1 Кбайт и не меняется с ростом N.)

In [8]:
a=4
b=5
c=True
a<<b=c

SyntaxError: cannot assign to operator (2864765088.py, line 4)